name: oneshot
description: unofficial apex companion app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  hive: ^2.2.3
  path_provider: ^2.0.11
  provider: ^6.0.3
  collection: ^1.16.0
  flutter_svg: ^1.1.1+1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/weapon/
    - assets/images/ammoType/
    - assets/images/fireMode/
    - assets/images/legendType/
    - assets/images/heal/
    - assets/images/optic/
    - assets/images/season/
    - assets/images/attachment/
    - assets/images/legend/
    - assets/images/legend/ash/
    - assets/images/legend/bangalore/
    - assets/images/legend/bloodhound/
    - assets/images/legend/caustic/
    - assets/images/legend/crypto/
    - assets/images/legend/fade/
    - assets/images/legend/fuse/
    - assets/images/legend/gibraltar/
    - assets/images/legend/horizon/
    - assets/images/legend/lifeline/
    - assets/images/legend/loba/
    - assets/images/legend/madmaggie/
    - assets/images/legend/mirage/
    - assets/images/legend/newcastle/
    - assets/images/legend/octane/
    - assets/images/legend/pathfinder/
    - assets/images/legend/rampart/
    - assets/images/legend/revenant/
    - assets/images/legend/seer/
    - assets/images/legend/valkyrie/
    - assets/images/legend/wattson/
    - assets/images/legend/wraith/
